# Generated by Django 5.1.5 on 2025-07-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0020_alter_item_options_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否核销')),
                ('verify_date', models.DateField(blank=True, null=True, verbose_name='核销日期')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_record', to='orders.order')),
            ],
            options={
                'verbose_name': '财务记录',
                'verbose_name_plural': '财务记录',
            },
        ),
    ]
