# Generated by Django 5.1.5 on 2025-07-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financerecord',
            options={'ordering': ['-verify_date', 'order__order_number'], 'verbose_name': '财务记录', 'verbose_name_plural': '财务记录'},
        ),
    ]
