# Generated by Django 5.1.5 on 2025-02-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='模板名称'),
        ),
    ]
