# Generated by Django 5.1.5 on 2025-02-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_template', '0003_customtemplate_field_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
