# Generated by Django 5.1.5 on 2025-02-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_template', '0004_alter_customtemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
