# Generated by Django 5.1.5 on 2025-07-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_template', '0005_alter_customtemplate_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtemplate',
            options={'verbose_name': '自定义模板', 'verbose_name_plural': '自定义模板'},
        ),
    ]
