# Generated by Django 5.1.5 on 2025-02-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='到站'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='送（提）货费'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='交货方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='departure_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发站'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='货物价值'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='保险费'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_maker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='制单人'),
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='包装费'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_sign',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收货人签名'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_sign',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发货人签名'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='运输方式'),
        ),
    ]
