# Generated by Django 5.1.5 on 2025-02-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_arrival_station_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transfer_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_order_no',
            field=models.DecimalField(decimal_places=2, default='111', max_digits=10, verbose_name='客户单号'),
        ),
    ]
