# Generated by Django 5.1.5 on 2025-02-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_order_no',
            field=models.DecimalField(decimal_places=2, default='111.00', max_digits=10, verbose_name='客户单号'),
        ),
    ]
