# Generated by Django 5.1.5 on 2025-02-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_customer_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default='12.00', max_digits=10, verbose_name='其他支出'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_freight',
            field=models.DecimalField(decimal_places=2, default='12.00', max_digits=10, verbose_name='总运费'),
        ),
    ]
