# Generated by Django 5.1.5 on 2025-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_other_expenses_alter_order_total_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_order_no',
            field=models.CharField(default='', max_length=50, verbose_name='客户单号'),
        ),
    ]
