# Generated by Django 5.1.5 on 2025-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_customer_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='货号'),
        ),
    ]
