# Generated by Django 5.1.5 on 2025-02-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_product_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_no',
            new_name='product_code',
        ),
    ]
