# Generated by Django 5.1.5 on 2025-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_arrival_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier_net',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='insurance_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packaging_fee',
        ),
        migrations.AddField(
            model_name='item',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='送（提）货费'),
        ),
        migrations.AddField(
            model_name='item',
            name='goods_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='货物价值'),
        ),
        migrations.AddField(
            model_name='item',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='保险费'),
        ),
        migrations.AddField(
            model_name='item',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='包装费'),
        ),
        migrations.AddField(
            model_name='item',
            name='remarks',
            field=models.CharField(default='无', max_length=50, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='arrival_address',
            field=models.CharField(default='Default Carrier_net', max_length=100, verbose_name='到站地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_address',
            field=models.CharField(default='Default Carrier_net', max_length=100, verbose_name='发站地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requirement',
            field=models.CharField(default='Default returnRequirement', max_length=50, verbose_name='回单要求'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrival_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='到站'),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发站'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_address',
            field=models.TextField(default='Default Carrier', verbose_name='收货详细地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_address',
            field=models.TextField(default='Default Carrier', verbose_name='发货详细地址'),
        ),
    ]
