# Generated by Django 5.1.5 on 2025-02-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='送（提）货费'),
        ),
        migrations.AlterField(
            model_name='item',
            name='goods_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='货物价值'),
        ),
        migrations.AlterField(
            model_name='item',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保险费'),
        ),
        migrations.AlterField(
            model_name='item',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='包装费'),
        ),
    ]
