# Generated by Django 5.1.5 on 2025-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='托运公司名称'),
        ),
    ]
