# Generated by Django 5.1.5 on 2025-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(verbose_name='重量(kg)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='托运公司名称'),
        ),
    ]
