# Generated by Django 5.1.5 on 2025-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(verbose_name='重量(kg)'),
        ),
    ]
