# Generated by Django 5.1.5 on 2025-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_item_weight_alter_order_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee_bai',
            field=models.CharField(blank=True, max_length=10, verbose_name='佰位金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_ge',
            field=models.CharField(blank=True, max_length=10, verbose_name='个位金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_qian',
            field=models.CharField(blank=True, max_length=10, verbose_name='仟位金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_shi',
            field=models.CharField(blank=True, max_length=10, verbose_name='拾位金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_wan',
            field=models.CharField(blank=True, max_length=10, verbose_name='万位金额'),
        ),
    ]
