# Generated by Django 5.1.5 on 2025-04-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_item_weight'),
        ('orders', '0017_order_fee_bai_order_fee_ge_order_fee_qian_and_more'),
    ]

    operations = [
    ]
