# Generated by Django 5.1.5 on 2025-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_merge_20250410_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_freight',
            field=models.IntegerField(default='12.00', verbose_name='总运费'),
        ),
    ]
