# Generated by Django 5.1.5 on 2025-07-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_total_freight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '新增订单', 'verbose_name_plural': '新增订单'},
        ),
    ]
