# Generated by Django 5.1.5 on 2025-07-14 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='订单编号')),
                ('departure', models.CharField(max_length=100, verbose_name='出发地')),
                ('destination', models.CharField(max_length=100, verbose_name='到达地')),
                ('shipper_name', models.CharField(max_length=50, verbose_name='发货人姓名')),
                ('shipper_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入有效的手机号码')], verbose_name='联系电话')),
                ('shipper_address', models.TextField(verbose_name='详细地址')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('receiver_address', models.TextField(verbose_name='详细地址')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('package_type', models.CharField(max_length=50, verbose_name='包装类型')),
                ('quantity', models.PositiveIntegerField(verbose_name='件数')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量(kg)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='体积(m³)')),
                ('delivery_method', models.CharField(max_length=20, verbose_name='交货方式')),
                ('transport_type', models.CharField(choices=[('fast', '快运'), ('normal', '普通运输')], max_length=20, verbose_name='运输要求')),
                ('payment_method', models.CharField(choices=[('prepay', '提付'), ('collect', '到付')], max_length=20, verbose_name='付款方式')),
                ('receipt_requirements', models.TextField(blank=True, verbose_name='回单要求')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('status', models.CharField(default='待处理', max_length=20, verbose_name='订单状态')),
            ],
        ),
    ]
