# Generated by Django 5.1.5 on 2025-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(max_length=20, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='transport_type',
            field=models.CharField(max_length=20, verbose_name='运输要求'),
        ),
    ]
