# Generated by Django 5.1.5 on 2025-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0002_alter_customerorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='volume',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='体积(m³)'),
        ),
    ]
