# Generated by Django 5.1.5 on 2025-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0003_alter_customerorder_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_method',
            field=models.CharField(choices=[('self', '自提'), ('delivery', '送货上门')], max_length=20, verbose_name='交货方式'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(choices=[('pickup', '提付'), ('delivery', '到付')], max_length=20, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='transport_type',
            field=models.CharField(choices=[('express', '快运'), ('standard', '普通运输')], max_length=20, verbose_name='运输要求'),
        ),
    ]
